export const COUPLE_NAME = 'Alia & Ariff'
export const WEDDING_TARGET_ISO = '2026-12-26T11:00:00'
export const WEDDING_DATE_LABEL = 'Saturday, 26 December 2026'
export const VENUE_NAME = 'Dewan Tan Sri Haji Ghazali Jawi'
export const VENUE_LOCATION = 'Slim River, Perak'
export const VENUE_ADDRESS_QUERY = 'Dewan Tan Sri Haji Ghazali Jawi, Slim River, Perak'
